# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "CS61A"
license = "MIT"
licenselink = "https://github.com/itsvs/hugo-theme-cs61a/blob/master/LICENSE.md"
description = "CS61A documentation theme for Hugo, based on Grav Learn theme"
homepage = "https://github.com/itsvs/hugo-theme-cs61a/"
repo = "https://github.com/itsvs/hugo-theme-cs61a"
tags = ["documentation", "grav", "learn", "doc", "search"]
features = ["documentation", "menu", "nested sections", "search", "mermaid"]
min_version = 0.25

[author]
  name = "Vanshaj Singhania"
  homepage = "https://imvs.me"

[original]
  name = "Mathieu Cornic"
  homepage = "https://matcornic.github.io/"
  repo = "https://github.com/matcornic/hugo-theme-learn"

[original]
  name = "Grav Learn"
  homepage = "https://learn.getgrav.org/"
  repo = "https://github.com/getgrav/grav-learn"
